Toast notification context
DeAlexandra/PaymentPortal pull request #6
Opened 2022-03-31 14:40 UTC by DeAlexandra

-created context for toast notifications
-changed the type of the toast notification
-added error notification for failed fetch on transaction list and user list

2022-03-31 15:11 UTC, enfrbhd requested changes

2022-04-01 06:57 UTC, DeAlexandra commented on src/components/DrawerMenu.jsx
> +                        { console.log(open) }
removed console.log

2022-04-01 06:59 UTC, DeAlexandra commented on src/App.js
> +  const [open, setOpen] = React.useState(false);
removed React.

2022-04-01 07:27 UTC, enfrbhd approved these changes

2022-04-01 07:27 UTC, merged